language: go

sudo: required

os:
- linux

go:
- "1.10.x"
- "1.11.x"
- stable

install:
- go get -u github.com/mgechev/revive
- go get -u github.com/go-swagger/go-swagger/cmd/swagger

stages:
- lint
- compile
- test

jobs:
  include:
  - stage: lint
    script:
    - make vet
    - make lint
  - stage: compile
    script:
    - make generate
    - make compile
  - stage: test
    script:
    - make cover