// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExecutionCommon Execution Common
//
// The properties that are shared amongst all versions of the Execution model.
// swagger:model execution-common
type ExecutionCommon struct {

	// cause
	// Required: true
	Cause ExecutionCause `json:"cause"`

	// job Id
	// Required: true
	// Pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
	JobID *string `json:"jobId"`

	// script Id
	// Required: true
	// Pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
	ScriptID *string `json:"scriptId"`

	// script rev
	// Required: true
	ScriptRev *string `json:"scriptRev"`

	// status
	// Required: true
	Status ExecutionStatus `json:"status"`
}

// Validate validates this execution common
func (m *ExecutionCommon) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCause(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJobID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScriptID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScriptRev(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExecutionCommon) validateCause(formats strfmt.Registry) error {

	if err := m.Cause.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("cause")
		}
		return err
	}

	return nil
}

func (m *ExecutionCommon) validateJobID(formats strfmt.Registry) error {

	if err := validate.Required("jobId", "body", m.JobID); err != nil {
		return err
	}

	if err := validate.Pattern("jobId", "body", string(*m.JobID), `[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`); err != nil {
		return err
	}

	return nil
}

func (m *ExecutionCommon) validateScriptID(formats strfmt.Registry) error {

	if err := validate.Required("scriptId", "body", m.ScriptID); err != nil {
		return err
	}

	if err := validate.Pattern("scriptId", "body", string(*m.ScriptID), `[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`); err != nil {
		return err
	}

	return nil
}

func (m *ExecutionCommon) validateScriptRev(formats strfmt.Registry) error {

	if err := validate.Required("scriptRev", "body", m.ScriptRev); err != nil {
		return err
	}

	return nil
}

func (m *ExecutionCommon) validateStatus(formats strfmt.Registry) error {

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExecutionCommon) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExecutionCommon) UnmarshalBinary(b []byte) error {
	var res ExecutionCommon
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
