// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ProjectOutputDetailed Project Output Detailed
//
// The properties that are included when fetching a single Project.
// swagger:model project-output-detailed
type ProjectOutputDetailed struct {
	ProjectEntity
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProjectOutputDetailed) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ProjectEntity
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ProjectEntity = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProjectOutputDetailed) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ProjectEntity)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this project output detailed
func (m *ProjectOutputDetailed) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectOutputDetailed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectOutputDetailed) UnmarshalBinary(b []byte) error {
	var res ProjectOutputDetailed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
