// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ProjectCommon Project Common
//
// The properties that are shared amongst all versions of the Project model.
// swagger:model project-common
type ProjectCommon struct {
	Definition
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProjectCommon) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Definition
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Definition = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProjectCommon) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.Definition)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this project common
func (m *ProjectCommon) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectCommon) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectCommon) UnmarshalBinary(b []byte) error {
	var res ProjectCommon
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
