// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ProjectUpdate Project Update
//
// The properties that are allowed when updating a Project.
// swagger:model project-update
type ProjectUpdate struct {
	ProjectCommon
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProjectUpdate) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ProjectCommon
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ProjectCommon = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProjectUpdate) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ProjectCommon)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this project update
func (m *ProjectUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectUpdate) UnmarshalBinary(b []byte) error {
	var res ProjectUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
