// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ScriptPersistence Script Persistence
// swagger:model script-persistence
type ScriptPersistence struct {

	// local
	Local string `json:"local,omitempty"`

	// remote
	Remote []string `json:"remote"`
}

// Validate validates this script persistence
func (m *ScriptPersistence) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScriptPersistence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScriptPersistence) UnmarshalBinary(b []byte) error {
	var res ScriptPersistence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
