// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/MontFerret/ferret-server/server/http/api/models"
)

// CreateScriptCreatedCode is the HTTP code returned for type CreateScriptCreated
const CreateScriptCreatedCode int = 201

/*CreateScriptCreated create script created

swagger:response createScriptCreated
*/
type CreateScriptCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Entity `json:"body,omitempty"`
}

// NewCreateScriptCreated creates CreateScriptCreated with default headers values
func NewCreateScriptCreated() *CreateScriptCreated {

	return &CreateScriptCreated{}
}

// WithPayload adds the payload to the create script created response
func (o *CreateScriptCreated) WithPayload(payload *models.Entity) *CreateScriptCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create script created response
func (o *CreateScriptCreated) SetPayload(payload *models.Entity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateScriptCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
