// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// CreateExecutionHandlerFunc turns a function with the right signature into a create execution handler
type CreateExecutionHandlerFunc func(CreateExecutionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateExecutionHandlerFunc) Handle(params CreateExecutionParams) middleware.Responder {
	return fn(params)
}

// CreateExecutionHandler interface for that can handle valid create execution params
type CreateExecutionHandler interface {
	Handle(CreateExecutionParams) middleware.Responder
}

// NewCreateExecution creates a new http.Handler for the create execution operation
func NewCreateExecution(ctx *middleware.Context, handler CreateExecutionHandler) *CreateExecution {
	return &CreateExecution{Context: ctx, Handler: handler}
}

/*CreateExecution swagger:route POST /projects/{projectId}/exec createExecution

Create Execution

*/
type CreateExecution struct {
	Context *middleware.Context
	Handler CreateExecutionHandler
}

func (o *CreateExecution) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateExecutionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateExecutionOKBody create execution o k body
// swagger:model CreateExecutionOKBody
type CreateExecutionOKBody struct {

	// job Id
	// Required: true
	JobID *string `json:"jobId"`
}

// Validate validates this create execution o k body
func (o *CreateExecutionOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateJobID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateExecutionOKBody) validateJobID(formats strfmt.Registry) error {

	if err := validate.Required("createExecutionOK"+"."+"jobId", "body", o.JobID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateExecutionOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateExecutionOKBody) UnmarshalBinary(b []byte) error {
	var res CreateExecutionOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
