// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateScriptHandlerFunc turns a function with the right signature into a create script handler
type CreateScriptHandlerFunc func(CreateScriptParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateScriptHandlerFunc) Handle(params CreateScriptParams) middleware.Responder {
	return fn(params)
}

// CreateScriptHandler interface for that can handle valid create script params
type CreateScriptHandler interface {
	Handle(CreateScriptParams) middleware.Responder
}

// NewCreateScript creates a new http.Handler for the create script operation
func NewCreateScript(ctx *middleware.Context, handler CreateScriptHandler) *CreateScript {
	return &CreateScript{Context: ctx, Handler: handler}
}

/*CreateScript swagger:route POST /projects/{projectId}/scripts createScript

Create Script

*/
type CreateScript struct {
	Context *middleware.Context
	Handler CreateScriptHandler
}

func (o *CreateScript) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateScriptParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
