// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateExecutionOKCode is the HTTP code returned for type CreateExecutionOK
const CreateExecutionOKCode int = 200

/*CreateExecutionOK create execution o k

swagger:response createExecutionOK
*/
type CreateExecutionOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateExecutionOK creates CreateExecutionOK with default headers values
func NewCreateExecutionOK() *CreateExecutionOK {

	return &CreateExecutionOK{}
}

// WithPayload adds the payload to the create execution o k response
func (o *CreateExecutionOK) WithPayload(payload string) *CreateExecutionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create execution o k response
func (o *CreateExecutionOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateExecutionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
