// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateExecutionHandlerFunc turns a function with the right signature into a create execution handler
type CreateExecutionHandlerFunc func(CreateExecutionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateExecutionHandlerFunc) Handle(params CreateExecutionParams) middleware.Responder {
	return fn(params)
}

// CreateExecutionHandler interface for that can handle valid create execution params
type CreateExecutionHandler interface {
	Handle(CreateExecutionParams) middleware.Responder
}

// NewCreateExecution creates a new http.Handler for the create execution operation
func NewCreateExecution(ctx *middleware.Context, handler CreateExecutionHandler) *CreateExecution {
	return &CreateExecution{Context: ctx, Handler: handler}
}

/*CreateExecution swagger:route POST /projects/{projectID}/exec createExecution

Create Execution

*/
type CreateExecution struct {
	Context *middleware.Context
	Handler CreateExecutionHandler
}

func (o *CreateExecution) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateExecutionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
