// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteScriptNoContentCode is the HTTP code returned for type DeleteScriptNoContent
const DeleteScriptNoContentCode int = 204

/*DeleteScriptNoContent delete script no content

swagger:response deleteScriptNoContent
*/
type DeleteScriptNoContent struct {
}

// NewDeleteScriptNoContent creates DeleteScriptNoContent with default headers values
func NewDeleteScriptNoContent() *DeleteScriptNoContent {

	return &DeleteScriptNoContent{}
}

// WriteResponse to the client
func (o *DeleteScriptNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
