// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteScriptDataHandlerFunc turns a function with the right signature into a delete script data handler
type DeleteScriptDataHandlerFunc func(DeleteScriptDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteScriptDataHandlerFunc) Handle(params DeleteScriptDataParams) middleware.Responder {
	return fn(params)
}

// DeleteScriptDataHandler interface for that can handle valid delete script data params
type DeleteScriptDataHandler interface {
	Handle(DeleteScriptDataParams) middleware.Responder
}

// NewDeleteScriptData creates a new http.Handler for the delete script data operation
func NewDeleteScriptData(ctx *middleware.Context, handler DeleteScriptDataHandler) *DeleteScriptData {
	return &DeleteScriptData{Context: ctx, Handler: handler}
}

/*DeleteScriptData swagger:route DELETE /projects/{projectId}/data/{scriptId}/{dataId} deleteScriptData

Delete Data

*/
type DeleteScriptData struct {
	Context *middleware.Context
	Handler DeleteScriptDataHandler
}

func (o *DeleteScriptData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteScriptDataParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
