// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteScriptHandlerFunc turns a function with the right signature into a delete script handler
type DeleteScriptHandlerFunc func(DeleteScriptParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteScriptHandlerFunc) Handle(params DeleteScriptParams) middleware.Responder {
	return fn(params)
}

// DeleteScriptHandler interface for that can handle valid delete script params
type DeleteScriptHandler interface {
	Handle(DeleteScriptParams) middleware.Responder
}

// NewDeleteScript creates a new http.Handler for the delete script operation
func NewDeleteScript(ctx *middleware.Context, handler DeleteScriptHandler) *DeleteScript {
	return &DeleteScript{Context: ctx, Handler: handler}
}

/*DeleteScript swagger:route DELETE /projects/{projectId}/scripts/{scriptId} deleteScript

Delete Script

*/
type DeleteScript struct {
	Context *middleware.Context
	Handler DeleteScriptHandler
}

func (o *DeleteScript) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteScriptParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
