// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteExecutionNoContentCode is the HTTP code returned for type DeleteExecutionNoContent
const DeleteExecutionNoContentCode int = 204

/*DeleteExecutionNoContent delete execution no content

swagger:response deleteExecutionNoContent
*/
type DeleteExecutionNoContent struct {
}

// NewDeleteExecutionNoContent creates DeleteExecutionNoContent with default headers values
func NewDeleteExecutionNoContent() *DeleteExecutionNoContent {

	return &DeleteExecutionNoContent{}
}

// WriteResponse to the client
func (o *DeleteExecutionNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
