// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FindExecutionsOKCode is the HTTP code returned for type FindExecutionsOK
const FindExecutionsOKCode int = 200

/*FindExecutionsOK find executions o k

swagger:response findExecutionsOK
*/
type FindExecutionsOK struct {

	/*
	  In: Body
	*/
	Payload *FindExecutionsOKBody `json:"body,omitempty"`
}

// NewFindExecutionsOK creates FindExecutionsOK with default headers values
func NewFindExecutionsOK() *FindExecutionsOK {

	return &FindExecutionsOK{}
}

// WithPayload adds the payload to the find executions o k response
func (o *FindExecutionsOK) WithPayload(payload *FindExecutionsOKBody) *FindExecutionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find executions o k response
func (o *FindExecutionsOK) SetPayload(payload *FindExecutionsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindExecutionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
