// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FindScriptDataOKCode is the HTTP code returned for type FindScriptDataOK
const FindScriptDataOKCode int = 200

/*FindScriptDataOK find script data o k

swagger:response findScriptDataOK
*/
type FindScriptDataOK struct {

	/*
	  In: Body
	*/
	Payload *FindScriptDataOKBody `json:"body,omitempty"`
}

// NewFindScriptDataOK creates FindScriptDataOK with default headers values
func NewFindScriptDataOK() *FindScriptDataOK {

	return &FindScriptDataOK{}
}

// WithPayload adds the payload to the find script data o k response
func (o *FindScriptDataOK) WithPayload(payload *FindScriptDataOKBody) *FindScriptDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find script data o k response
func (o *FindScriptDataOK) SetPayload(payload *FindScriptDataOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindScriptDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
