// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FindScriptDataOKCode is the HTTP code returned for type FindScriptDataOK
const FindScriptDataOKCode int = 200

/*FindScriptDataOK find script data o k

swagger:response findScriptDataOK
*/
type FindScriptDataOK struct {

	/*
	  In: Body
	*/
	Payload []*FindScriptDataOKBodyItems0 `json:"body,omitempty"`
}

// NewFindScriptDataOK creates FindScriptDataOK with default headers values
func NewFindScriptDataOK() *FindScriptDataOK {

	return &FindScriptDataOK{}
}

// WithPayload adds the payload to the find script data o k response
func (o *FindScriptDataOK) WithPayload(payload []*FindScriptDataOKBodyItems0) *FindScriptDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find script data o k response
func (o *FindScriptDataOK) SetPayload(payload []*FindScriptDataOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindScriptDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*FindScriptDataOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
