// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/MontFerret/ferret-server/server/http/api/models"
)

// GetExecutionOKCode is the HTTP code returned for type GetExecutionOK
const GetExecutionOKCode int = 200

/*GetExecutionOK get execution o k

swagger:response getExecutionOK
*/
type GetExecutionOK struct {

	/*
	  In: Body
	*/
	Payload *models.ExecutionOutputDetailed `json:"body,omitempty"`
}

// NewGetExecutionOK creates GetExecutionOK with default headers values
func NewGetExecutionOK() *GetExecutionOK {

	return &GetExecutionOK{}
}

// WithPayload adds the payload to the get execution o k response
func (o *GetExecutionOK) WithPayload(payload *models.ExecutionOutputDetailed) *GetExecutionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get execution o k response
func (o *GetExecutionOK) SetPayload(payload *models.ExecutionOutputDetailed) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetExecutionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
