// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// UpdateScriptDataURL generates an URL for the update script data operation
type UpdateScriptDataURL struct {
	DataID    string
	ProjectID string
	ScriptID  string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateScriptDataURL) WithBasePath(bp string) *UpdateScriptDataURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateScriptDataURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *UpdateScriptDataURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/projects/{projectID}/data/{scriptID}/{dataId}"

	dataID := o.DataID
	if dataID != "" {
		_path = strings.Replace(_path, "{dataId}", dataID, -1)
	} else {
		return nil, errors.New("dataId is required on UpdateScriptDataURL")
	}

	projectID := o.ProjectID
	if projectID != "" {
		_path = strings.Replace(_path, "{projectID}", projectID, -1)
	} else {
		return nil, errors.New("projectId is required on UpdateScriptDataURL")
	}

	scriptID := o.ScriptID
	if scriptID != "" {
		_path = strings.Replace(_path, "{scriptID}", scriptID, -1)
	} else {
		return nil, errors.New("scriptId is required on UpdateScriptDataURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *UpdateScriptDataURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *UpdateScriptDataURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *UpdateScriptDataURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on UpdateScriptDataURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on UpdateScriptDataURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *UpdateScriptDataURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
