// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateScriptHandlerFunc turns a function with the right signature into a update script handler
type UpdateScriptHandlerFunc func(UpdateScriptParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateScriptHandlerFunc) Handle(params UpdateScriptParams) middleware.Responder {
	return fn(params)
}

// UpdateScriptHandler interface for that can handle valid update script params
type UpdateScriptHandler interface {
	Handle(UpdateScriptParams) middleware.Responder
}

// NewUpdateScript creates a new http.Handler for the update script operation
func NewUpdateScript(ctx *middleware.Context, handler UpdateScriptHandler) *UpdateScript {
	return &UpdateScript{Context: ctx, Handler: handler}
}

/*UpdateScript swagger:route PUT /projects/{projectId}/scripts/{scriptId} updateScript

Update Script

*/
type UpdateScript struct {
	Context *middleware.Context
	Handler UpdateScriptHandler
}

func (o *UpdateScript) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateScriptParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
