// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateScriptDataHandlerFunc turns a function with the right signature into a update script data handler
type UpdateScriptDataHandlerFunc func(UpdateScriptDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateScriptDataHandlerFunc) Handle(params UpdateScriptDataParams) middleware.Responder {
	return fn(params)
}

// UpdateScriptDataHandler interface for that can handle valid update script data params
type UpdateScriptDataHandler interface {
	Handle(UpdateScriptDataParams) middleware.Responder
}

// NewUpdateScriptData creates a new http.Handler for the update script data operation
func NewUpdateScriptData(ctx *middleware.Context, handler UpdateScriptDataHandler) *UpdateScriptData {
	return &UpdateScriptData{Context: ctx, Handler: handler}
}

/*UpdateScriptData swagger:route PUT /projects/{projectId}/data/{scriptId}/{dataId} updateScriptData

Update Data

*/
type UpdateScriptData struct {
	Context *middleware.Context
	Handler UpdateScriptDataHandler
}

func (o *UpdateScriptData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateScriptDataParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
