// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Ferret Server API
API of Ferret Server


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0-rc.2
    License: MIT
    Contact: MontFerret Project Group<mont.ferret@gmail.com> https://github.com/MontFerret

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
