// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Ferret Server API
API of Ferret Server


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1
    License: MIT
    Contact: Tim Voronov<ziflex@gmail.com> https://github.com/ziflex

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
