// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API of Ferret Server",
    "title": "Ferret Server API",
    "contact": {
      "name": "Tim Voronov",
      "url": "https://github.com/ziflex",
      "email": "ziflex@gmail.com"
    },
    "license": {
      "name": "MIT"
    },
    "version": "0.1"
  },
  "paths": {
    "/projects": {
      "get": {
        "summary": "List Project",
        "operationId": "findProjects",
        "parameters": [
          {
            "$ref": "#/parameters/page"
          },
          {
            "$ref": "#/parameters/size"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/project-output"
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create Project",
        "operationId": "createProject",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/project-create"
            }
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "$ref": "#/definitions/entity"
            }
          }
        }
      }
    },
    "/projects/{projectID}": {
      "get": {
        "summary": "Get Project",
        "operationId": "getProject",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/project-output-detailed"
            }
          }
        }
      },
      "put": {
        "summary": "Update Project",
        "operationId": "updateProject",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/project-update"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/entity"
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Project",
        "operationId": "deleteProject",
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/projectID"
        }
      ]
    },
    "/projects/{projectID}/data": {
      "get": {
        "summary": "List Data",
        "operationId": "findProjectData",
        "parameters": [
          {
            "$ref": "#/parameters/page"
          },
          {
            "$ref": "#/parameters/size"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/data-output"
              }
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/data/{scriptID}": {
      "get": {
        "summary": "List Script Data",
        "operationId": "findScriptData",
        "parameters": [
          {
            "$ref": "#/parameters/page"
          },
          {
            "$ref": "#/parameters/size"
          },
          {
            "$ref": "#/parameters/scriptID"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/data-output"
              }
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "scriptID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/data/{scriptID}/{dataId}": {
      "get": {
        "summary": "Get Data",
        "operationId": "getScriptData",
        "parameters": [
          {
            "$ref": "#/parameters/scriptID"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/data-output-detailed"
            }
          }
        }
      },
      "put": {
        "summary": "Update Data",
        "operationId": "updateScriptData",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/data-update"
            }
          },
          {
            "$ref": "#/parameters/scriptID"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/entity"
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Data",
        "operationId": "deleteScriptData",
        "parameters": [
          {
            "$ref": "#/parameters/scriptID"
          }
        ],
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "scriptID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "dataId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/execution": {
      "get": {
        "summary": "List Execution",
        "operationId": "findExecutions",
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/execution-output"
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create Execution",
        "operationId": "createExecution",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/execution-input"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/projectID"
        },
        {
          "$ref": "#/parameters/status"
        }
      ]
    },
    "/projects/{projectID}/execution/{jobID}": {
      "get": {
        "summary": "Get Status of Execution",
        "operationId": "getExecution",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/execution-output-detailed"
            }
          }
        }
      },
      "delete": {
        "summary": "Cancel Execution",
        "operationId": "deleteExecution",
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/projectID"
        },
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "jobID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/scripts": {
      "get": {
        "summary": "List Script",
        "operationId": "findScripts",
        "parameters": [
          {
            "$ref": "#/parameters/page"
          },
          {
            "$ref": "#/parameters/size"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/script-output"
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create Script",
        "operationId": "createScript",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/script-create"
            }
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "$ref": "#/definitions/entity"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/projectID"
        }
      ]
    },
    "/projects/{projectID}/scripts/{scriptID}": {
      "get": {
        "summary": "Get Script",
        "operationId": "getScript",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/script-output-detailed"
            }
          }
        }
      },
      "put": {
        "summary": "Update Script",
        "operationId": "updateScript",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/script-create"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/entity"
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Script",
        "operationId": "deleteScript",
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/projectID"
        },
        {
          "$ref": "#/parameters/scriptID"
        }
      ]
    }
  },
  "definitions": {
    "any": {
      "title": "Any"
    },
    "data-common": {
      "description": "The properties that are shared amongst all versions of the Data model.",
      "type": "object",
      "title": "Data Common",
      "required": [
        "job_id",
        "script_id",
        "script_rev",
        "value"
      ],
      "properties": {
        "job_id": {
          "type": "string"
        },
        "script_id": {
          "type": "string"
        },
        "script_rev": {
          "type": "string"
        },
        "value": {
          "$ref": "#/definitions/any"
        }
      }
    },
    "data-entity": {
      "title": "Data Entity",
      "allOf": [
        {
          "$ref": "#/definitions/entity"
        },
        {
          "$ref": "#/definitions/data-common"
        }
      ]
    },
    "data-output": {
      "description": "The properties that are included when fetching a list of Data.",
      "title": "Data Output",
      "allOf": [
        {
          "$ref": "#/definitions/entity"
        },
        {
          "type": "object",
          "required": [
            "job_id",
            "script_id"
          ],
          "properties": {
            "job_id": {
              "type": "string"
            },
            "script_id": {
              "type": "string"
            },
            "script_rev": {
              "type": "string"
            }
          }
        }
      ]
    },
    "data-output-detailed": {
      "description": "The properties that are included when fetching a single Data.",
      "title": "Data Output Detailed",
      "allOf": [
        {
          "$ref": "#/definitions/data-entity"
        }
      ]
    },
    "data-update": {
      "description": "The properties that are allowed when updating a Data.",
      "type": "object",
      "title": "Data Update",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "$ref": "#/definitions/any"
        }
      }
    },
    "entity": {
      "description": "Represents a database entity",
      "title": "Entity",
      "allOf": [
        {
          "type": "object",
          "required": [
            "id",
            "rev"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "rev": {
              "type": "string"
            }
          }
        },
        {
          "$ref": "#/definitions/metadata"
        }
      ]
    },
    "execution-cause": {
      "description": "Execution cause",
      "type": "string",
      "title": "Execution Cause",
      "enum": [
        "unknown",
        "manual",
        "schedule",
        "hook"
      ]
    },
    "execution-common": {
      "description": "The properties that are shared amongst all versions of the Execution model.",
      "type": "object",
      "title": "Execution Common",
      "required": [
        "job_id",
        "script_id",
        "script_rev",
        "status",
        "cause"
      ],
      "properties": {
        "cause": {
          "$ref": "#/definitions/execution-cause"
        },
        "job_id": {
          "type": "string",
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        },
        "script_id": {
          "type": "string",
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        },
        "script_rev": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/execution-status"
        }
      }
    },
    "execution-input": {
      "description": "The properties that are allowed when creating or updating a Execution.",
      "type": "object",
      "title": "Execution Input",
      "required": [
        "scriptID"
      ],
      "properties": {
        "params": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/any"
          }
        },
        "scriptID": {
          "type": "string",
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        }
      }
    },
    "execution-output": {
      "description": "The properties that are included when fetching a list of Executions.",
      "title": "Execution Output",
      "allOf": [
        {
          "type": "object"
        },
        {
          "$ref": "#/definitions/execution-common"
        }
      ]
    },
    "execution-output-detailed": {
      "description": "The properties that are included when fetching a single Execution.",
      "title": "Execution Output Detailed",
      "allOf": [
        {
          "$ref": "#/definitions/execution-output"
        },
        {
          "type": "object",
          "properties": {
            "ended_at": {
              "type": "string"
            },
            "error": {
              "type": "string"
            },
            "logs": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "params": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/definitions/any"
              }
            },
            "started_at": {
              "type": "string"
            }
          }
        }
      ]
    },
    "execution-status": {
      "description": "Execution stats",
      "type": "string",
      "title": "Execution Status",
      "enum": [
        "unknown",
        "queued",
        "running",
        "completed",
        "cancelled",
        "errored"
      ]
    },
    "metadata": {
      "description": "Response model for data creation endpoints",
      "type": "object",
      "title": "Metadata",
      "required": [
        "created_at"
      ],
      "properties": {
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        }
      }
    },
    "project-common": {
      "description": "The properties that are shared amongst all versions of the Project model.",
      "type": "object",
      "title": "Project Common",
      "required": [
        "name"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        }
      }
    },
    "project-create": {
      "title": "Project Create",
      "$ref": "#/definitions/project-common"
    },
    "project-entity": {
      "description": "Represents a full Project entity.",
      "title": "Project Entity",
      "allOf": [
        {
          "$ref": "#/definitions/entity"
        },
        {
          "$ref": "#/definitions/project-common"
        }
      ]
    },
    "project-output": {
      "description": "The properties that are included when fetching a list of Projects.",
      "title": "Project Output",
      "allOf": [
        {
          "$ref": "#/definitions/entity"
        },
        {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "project-output-detailed": {
      "description": "The properties that are included when fetching a single Project.",
      "title": "Project Output Detailed",
      "$ref": "#/definitions/project-entity"
    },
    "project-update": {
      "description": "The properties that are allowed when updating a Project.",
      "title": "Project Update",
      "$ref": "#/definitions/project-common"
    },
    "script-common": {
      "description": "The properties that are shared amongst all versions of the Script model.",
      "type": "object",
      "title": "Script Common",
      "required": [
        "name",
        "execution",
        "persistence"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "execution": {
          "$ref": "#/definitions/script-execution"
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        },
        "persistence": {
          "$ref": "#/definitions/script-persistence"
        }
      }
    },
    "script-create": {
      "description": "The properties that are allowed when creating a Script.",
      "title": "Script Create",
      "$ref": "#/definitions/script-common"
    },
    "script-entity": {
      "title": "Script Entity",
      "allOf": [
        {
          "$ref": "#/definitions/entity"
        },
        {
          "$ref": "#/definitions/script-common"
        }
      ]
    },
    "script-execution": {
      "description": "Represents script execution settings like query and params",
      "type": "object",
      "title": "Script Execution Settings",
      "required": [
        "query"
      ],
      "properties": {
        "params": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/any"
          }
        },
        "query": {
          "type": "string",
          "minLength": 8
        }
      }
    },
    "script-output": {
      "description": "The properties that are included when fetching a list of Scripts.",
      "title": "Script Output",
      "allOf": [
        {
          "$ref": "#/definitions/entity"
        },
        {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "script-output-detailed": {
      "description": "The properties that are included when fetching a single Script.",
      "title": "Script Output Detailed",
      "$ref": "#/definitions/script-entity"
    },
    "script-persistence": {
      "type": "object",
      "title": "Script Persistence",
      "required": [
        "enabled"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        }
      }
    },
    "script-update": {
      "description": "The properties that are allowed when updating a Script.",
      "title": "Script Update",
      "$ref": "#/definitions/script-common"
    }
  },
  "parameters": {
    "page": {
      "minimum": 1,
      "type": "integer",
      "format": "int32",
      "default": 1,
      "description": "Page number for queries",
      "name": "page",
      "in": "query"
    },
    "projectID": {
      "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
      "type": "string",
      "name": "projectID",
      "in": "path",
      "required": true
    },
    "scriptID": {
      "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
      "type": "string",
      "name": "scriptID",
      "in": "path",
      "required": true
    },
    "size": {
      "maximum": 100,
      "minimum": 1,
      "type": "integer",
      "format": "int32",
      "default": 10,
      "description": "Page size",
      "name": "size",
      "in": "query"
    },
    "status": {
      "enum": [
        "unknown",
        "queued",
        "running",
        "completed",
        "cancelled",
        "errored"
      ],
      "type": "string",
      "name": "status",
      "in": "query",
      "allowEmptyValue": true
    }
  },
  "responses": {
    "Error": {
      "description": "Error resonse",
      "schema": {
        "type": "string"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API of Ferret Server",
    "title": "Ferret Server API",
    "contact": {
      "name": "Tim Voronov",
      "url": "https://github.com/ziflex",
      "email": "ziflex@gmail.com"
    },
    "license": {
      "name": "MIT"
    },
    "version": "0.1"
  },
  "paths": {
    "/projects": {
      "get": {
        "summary": "List Project",
        "operationId": "findProjects",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 1,
            "description": "Page number for queries",
            "name": "page",
            "in": "query"
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 10,
            "description": "Page size",
            "name": "size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "description": "The properties that are included when fetching a list of Projects.",
                "title": "Project Output",
                "allOf": [
                  {
                    "description": "Represents a database entity",
                    "title": "Entity",
                    "allOf": [
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "rev"
                        ],
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "rev": {
                            "type": "string"
                          }
                        }
                      },
                      {
                        "description": "Response model for data creation endpoints",
                        "type": "object",
                        "title": "Metadata",
                        "required": [
                          "created_at"
                        ],
                        "properties": {
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "object",
                    "required": [
                      "name"
                    ],
                    "properties": {
                      "name": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create Project",
        "operationId": "createProject",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "The properties that are shared amongst all versions of the Project model.",
              "type": "object",
              "title": "Project Common",
              "required": [
                "name"
              ],
              "properties": {
                "description": {
                  "type": "string",
                  "maxLength": 255,
                  "minLength": 10
                },
                "name": {
                  "type": "string",
                  "maxLength": 100,
                  "minLength": 3
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "description": "Represents a database entity",
              "title": "Entity",
              "allOf": [
                {
                  "type": "object",
                  "required": [
                    "id",
                    "rev"
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "rev": {
                      "type": "string"
                    }
                  }
                },
                {
                  "description": "Response model for data creation endpoints",
                  "type": "object",
                  "title": "Metadata",
                  "required": [
                    "created_at"
                  ],
                  "properties": {
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    },
    "/projects/{projectID}": {
      "get": {
        "summary": "Get Project",
        "operationId": "getProject",
        "responses": {
          "200": {
            "schema": {
              "description": "Represents a full Project entity.",
              "title": "Project Entity",
              "allOf": [
                {
                  "description": "Represents a database entity",
                  "title": "Entity",
                  "allOf": [
                    {
                      "type": "object",
                      "required": [
                        "id",
                        "rev"
                      ],
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "rev": {
                          "type": "string"
                        }
                      }
                    },
                    {
                      "description": "Response model for data creation endpoints",
                      "type": "object",
                      "title": "Metadata",
                      "required": [
                        "created_at"
                      ],
                      "properties": {
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                {
                  "description": "The properties that are shared amongst all versions of the Project model.",
                  "type": "object",
                  "title": "Project Common",
                  "required": [
                    "name"
                  ],
                  "properties": {
                    "description": {
                      "type": "string",
                      "maxLength": 255,
                      "minLength": 10
                    },
                    "name": {
                      "type": "string",
                      "maxLength": 100,
                      "minLength": 3
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "put": {
        "summary": "Update Project",
        "operationId": "updateProject",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "The properties that are shared amongst all versions of the Project model.",
              "type": "object",
              "title": "Project Common",
              "required": [
                "name"
              ],
              "properties": {
                "description": {
                  "type": "string",
                  "maxLength": 255,
                  "minLength": 10
                },
                "name": {
                  "type": "string",
                  "maxLength": 100,
                  "minLength": 3
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "Represents a database entity",
              "title": "Entity",
              "allOf": [
                {
                  "type": "object",
                  "required": [
                    "id",
                    "rev"
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "rev": {
                      "type": "string"
                    }
                  }
                },
                {
                  "description": "Response model for data creation endpoints",
                  "type": "object",
                  "title": "Metadata",
                  "required": [
                    "created_at"
                  ],
                  "properties": {
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Project",
        "operationId": "deleteProject",
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/data": {
      "get": {
        "summary": "List Data",
        "operationId": "findProjectData",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 1,
            "description": "Page number for queries",
            "name": "page",
            "in": "query"
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 10,
            "description": "Page size",
            "name": "size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "description": "The properties that are included when fetching a list of Data.",
                "title": "Data Output",
                "allOf": [
                  {
                    "description": "Represents a database entity",
                    "title": "Entity",
                    "allOf": [
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "rev"
                        ],
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "rev": {
                            "type": "string"
                          }
                        }
                      },
                      {
                        "description": "Response model for data creation endpoints",
                        "type": "object",
                        "title": "Metadata",
                        "required": [
                          "created_at"
                        ],
                        "properties": {
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "object",
                    "required": [
                      "job_id",
                      "script_id"
                    ],
                    "properties": {
                      "job_id": {
                        "type": "string"
                      },
                      "script_id": {
                        "type": "string"
                      },
                      "script_rev": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/data/{scriptID}": {
      "get": {
        "summary": "List Script Data",
        "operationId": "findScriptData",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 1,
            "description": "Page number for queries",
            "name": "page",
            "in": "query"
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 10,
            "description": "Page size",
            "name": "size",
            "in": "query"
          },
          {
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            "type": "string",
            "name": "scriptID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "description": "The properties that are included when fetching a list of Data.",
                "title": "Data Output",
                "allOf": [
                  {
                    "description": "Represents a database entity",
                    "title": "Entity",
                    "allOf": [
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "rev"
                        ],
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "rev": {
                            "type": "string"
                          }
                        }
                      },
                      {
                        "description": "Response model for data creation endpoints",
                        "type": "object",
                        "title": "Metadata",
                        "required": [
                          "created_at"
                        ],
                        "properties": {
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "object",
                    "required": [
                      "job_id",
                      "script_id"
                    ],
                    "properties": {
                      "job_id": {
                        "type": "string"
                      },
                      "script_id": {
                        "type": "string"
                      },
                      "script_rev": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "scriptID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/data/{scriptID}/{dataId}": {
      "get": {
        "summary": "Get Data",
        "operationId": "getScriptData",
        "parameters": [
          {
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            "type": "string",
            "name": "scriptID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "The properties that are included when fetching a single Data.",
              "title": "Data Output Detailed",
              "allOf": [
                {
                  "title": "Data Entity",
                  "allOf": [
                    {
                      "description": "Represents a database entity",
                      "title": "Entity",
                      "allOf": [
                        {
                          "type": "object",
                          "required": [
                            "id",
                            "rev"
                          ],
                          "properties": {
                            "id": {
                              "type": "string"
                            },
                            "rev": {
                              "type": "string"
                            }
                          }
                        },
                        {
                          "description": "Response model for data creation endpoints",
                          "type": "object",
                          "title": "Metadata",
                          "required": [
                            "created_at"
                          ],
                          "properties": {
                            "created_at": {
                              "type": "string"
                            },
                            "updated_at": {
                              "type": "string"
                            }
                          }
                        }
                      ]
                    },
                    {
                      "description": "The properties that are shared amongst all versions of the Data model.",
                      "type": "object",
                      "title": "Data Common",
                      "required": [
                        "job_id",
                        "script_id",
                        "script_rev",
                        "value"
                      ],
                      "properties": {
                        "job_id": {
                          "type": "string"
                        },
                        "script_id": {
                          "type": "string"
                        },
                        "script_rev": {
                          "type": "string"
                        },
                        "value": {
                          "title": "Any"
                        }
                      }
                    }
                  ]
                }
              ]
            }
          }
        }
      },
      "put": {
        "summary": "Update Data",
        "operationId": "updateScriptData",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "The properties that are allowed when updating a Data.",
              "type": "object",
              "title": "Data Update",
              "required": [
                "value"
              ],
              "properties": {
                "value": {
                  "title": "Any"
                }
              }
            }
          },
          {
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            "type": "string",
            "name": "scriptID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "Represents a database entity",
              "title": "Entity",
              "allOf": [
                {
                  "type": "object",
                  "required": [
                    "id",
                    "rev"
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "rev": {
                      "type": "string"
                    }
                  }
                },
                {
                  "description": "Response model for data creation endpoints",
                  "type": "object",
                  "title": "Metadata",
                  "required": [
                    "created_at"
                  ],
                  "properties": {
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Data",
        "operationId": "deleteScriptData",
        "parameters": [
          {
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            "type": "string",
            "name": "scriptID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "scriptID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "dataId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/execution": {
      "get": {
        "summary": "List Execution",
        "operationId": "findExecutions",
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "description": "The properties that are included when fetching a list of Executions.",
                "title": "Execution Output",
                "allOf": [
                  {
                    "type": "object"
                  },
                  {
                    "description": "The properties that are shared amongst all versions of the Execution model.",
                    "type": "object",
                    "title": "Execution Common",
                    "required": [
                      "job_id",
                      "script_id",
                      "script_rev",
                      "status",
                      "cause"
                    ],
                    "properties": {
                      "cause": {
                        "description": "Execution cause",
                        "type": "string",
                        "title": "Execution Cause",
                        "enum": [
                          "unknown",
                          "manual",
                          "schedule",
                          "hook"
                        ]
                      },
                      "job_id": {
                        "type": "string",
                        "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                      },
                      "script_id": {
                        "type": "string",
                        "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                      },
                      "script_rev": {
                        "type": "string"
                      },
                      "status": {
                        "description": "Execution stats",
                        "type": "string",
                        "title": "Execution Status",
                        "enum": [
                          "unknown",
                          "queued",
                          "running",
                          "completed",
                          "cancelled",
                          "errored"
                        ]
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create Execution",
        "operationId": "createExecution",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "The properties that are allowed when creating or updating a Execution.",
              "type": "object",
              "title": "Execution Input",
              "required": [
                "scriptID"
              ],
              "properties": {
                "params": {
                  "type": "object",
                  "additionalProperties": {
                    "title": "Any"
                  }
                },
                "scriptID": {
                  "type": "string",
                  "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "parameters": [
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        },
        {
          "enum": [
            "unknown",
            "queued",
            "running",
            "completed",
            "cancelled",
            "errored"
          ],
          "type": "string",
          "name": "status",
          "in": "query",
          "allowEmptyValue": true
        }
      ]
    },
    "/projects/{projectID}/execution/{jobID}": {
      "get": {
        "summary": "Get Status of Execution",
        "operationId": "getExecution",
        "responses": {
          "200": {
            "schema": {
              "description": "The properties that are included when fetching a single Execution.",
              "title": "Execution Output Detailed",
              "allOf": [
                {
                  "description": "The properties that are included when fetching a list of Executions.",
                  "title": "Execution Output",
                  "allOf": [
                    {
                      "type": "object"
                    },
                    {
                      "description": "The properties that are shared amongst all versions of the Execution model.",
                      "type": "object",
                      "title": "Execution Common",
                      "required": [
                        "job_id",
                        "script_id",
                        "script_rev",
                        "status",
                        "cause"
                      ],
                      "properties": {
                        "cause": {
                          "description": "Execution cause",
                          "type": "string",
                          "title": "Execution Cause",
                          "enum": [
                            "unknown",
                            "manual",
                            "schedule",
                            "hook"
                          ]
                        },
                        "job_id": {
                          "type": "string",
                          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                        },
                        "script_id": {
                          "type": "string",
                          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                        },
                        "script_rev": {
                          "type": "string"
                        },
                        "status": {
                          "description": "Execution stats",
                          "type": "string",
                          "title": "Execution Status",
                          "enum": [
                            "unknown",
                            "queued",
                            "running",
                            "completed",
                            "cancelled",
                            "errored"
                          ]
                        }
                      }
                    }
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "ended_at": {
                      "type": "string"
                    },
                    "error": {
                      "type": "string"
                    },
                    "logs": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "params": {
                      "type": "object",
                      "additionalProperties": {
                        "title": "Any"
                      }
                    },
                    "started_at": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "delete": {
        "summary": "Cancel Execution",
        "operationId": "deleteExecution",
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        },
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "jobID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/scripts": {
      "get": {
        "summary": "List Script",
        "operationId": "findScripts",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 1,
            "description": "Page number for queries",
            "name": "page",
            "in": "query"
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 10,
            "description": "Page size",
            "name": "size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": {
                "description": "The properties that are included when fetching a list of Scripts.",
                "title": "Script Output",
                "allOf": [
                  {
                    "description": "Represents a database entity",
                    "title": "Entity",
                    "allOf": [
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "rev"
                        ],
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "rev": {
                            "type": "string"
                          }
                        }
                      },
                      {
                        "description": "Response model for data creation endpoints",
                        "type": "object",
                        "title": "Metadata",
                        "required": [
                          "created_at"
                        ],
                        "properties": {
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "object",
                    "required": [
                      "name"
                    ],
                    "properties": {
                      "name": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create Script",
        "operationId": "createScript",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "The properties that are shared amongst all versions of the Script model.",
              "type": "object",
              "title": "Script Common",
              "required": [
                "name",
                "execution",
                "persistence"
              ],
              "properties": {
                "description": {
                  "type": "string",
                  "maxLength": 255,
                  "minLength": 10
                },
                "execution": {
                  "description": "Represents script execution settings like query and params",
                  "type": "object",
                  "title": "Script Execution Settings",
                  "required": [
                    "query"
                  ],
                  "properties": {
                    "params": {
                      "type": "object",
                      "additionalProperties": {
                        "title": "Any"
                      }
                    },
                    "query": {
                      "type": "string",
                      "minLength": 8
                    }
                  }
                },
                "name": {
                  "type": "string",
                  "maxLength": 100,
                  "minLength": 3
                },
                "persistence": {
                  "type": "object",
                  "title": "Script Persistence",
                  "required": [
                    "enabled"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "description": "Represents a database entity",
              "title": "Entity",
              "allOf": [
                {
                  "type": "object",
                  "required": [
                    "id",
                    "rev"
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "rev": {
                      "type": "string"
                    }
                  }
                },
                {
                  "description": "Response model for data creation endpoints",
                  "type": "object",
                  "title": "Metadata",
                  "required": [
                    "created_at"
                  ],
                  "properties": {
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "parameters": [
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/projects/{projectID}/scripts/{scriptID}": {
      "get": {
        "summary": "Get Script",
        "operationId": "getScript",
        "responses": {
          "200": {
            "schema": {
              "title": "Script Entity",
              "allOf": [
                {
                  "description": "Represents a database entity",
                  "title": "Entity",
                  "allOf": [
                    {
                      "type": "object",
                      "required": [
                        "id",
                        "rev"
                      ],
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "rev": {
                          "type": "string"
                        }
                      }
                    },
                    {
                      "description": "Response model for data creation endpoints",
                      "type": "object",
                      "title": "Metadata",
                      "required": [
                        "created_at"
                      ],
                      "properties": {
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                {
                  "description": "The properties that are shared amongst all versions of the Script model.",
                  "type": "object",
                  "title": "Script Common",
                  "required": [
                    "name",
                    "execution",
                    "persistence"
                  ],
                  "properties": {
                    "description": {
                      "type": "string",
                      "maxLength": 255,
                      "minLength": 10
                    },
                    "execution": {
                      "description": "Represents script execution settings like query and params",
                      "type": "object",
                      "title": "Script Execution Settings",
                      "required": [
                        "query"
                      ],
                      "properties": {
                        "params": {
                          "type": "object",
                          "additionalProperties": {
                            "title": "Any"
                          }
                        },
                        "query": {
                          "type": "string",
                          "minLength": 8
                        }
                      }
                    },
                    "name": {
                      "type": "string",
                      "maxLength": 100,
                      "minLength": 3
                    },
                    "persistence": {
                      "type": "object",
                      "title": "Script Persistence",
                      "required": [
                        "enabled"
                      ],
                      "properties": {
                        "enabled": {
                          "type": "boolean"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "put": {
        "summary": "Update Script",
        "operationId": "updateScript",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "The properties that are shared amongst all versions of the Script model.",
              "type": "object",
              "title": "Script Common",
              "required": [
                "name",
                "execution",
                "persistence"
              ],
              "properties": {
                "description": {
                  "type": "string",
                  "maxLength": 255,
                  "minLength": 10
                },
                "execution": {
                  "description": "Represents script execution settings like query and params",
                  "type": "object",
                  "title": "Script Execution Settings",
                  "required": [
                    "query"
                  ],
                  "properties": {
                    "params": {
                      "type": "object",
                      "additionalProperties": {
                        "title": "Any"
                      }
                    },
                    "query": {
                      "type": "string",
                      "minLength": 8
                    }
                  }
                },
                "name": {
                  "type": "string",
                  "maxLength": 100,
                  "minLength": 3
                },
                "persistence": {
                  "type": "object",
                  "title": "Script Persistence",
                  "required": [
                    "enabled"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "Represents a database entity",
              "title": "Entity",
              "allOf": [
                {
                  "type": "object",
                  "required": [
                    "id",
                    "rev"
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "rev": {
                      "type": "string"
                    }
                  }
                },
                {
                  "description": "Response model for data creation endpoints",
                  "type": "object",
                  "title": "Metadata",
                  "required": [
                    "created_at"
                  ],
                  "properties": {
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "delete": {
        "summary": "Delete Script",
        "operationId": "deleteScript",
        "responses": {
          "204": {}
        }
      },
      "parameters": [
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "projectID",
          "in": "path",
          "required": true
        },
        {
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
          "type": "string",
          "name": "scriptID",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "any": {
      "title": "Any"
    },
    "data-common": {
      "description": "The properties that are shared amongst all versions of the Data model.",
      "type": "object",
      "title": "Data Common",
      "required": [
        "job_id",
        "script_id",
        "script_rev",
        "value"
      ],
      "properties": {
        "job_id": {
          "type": "string"
        },
        "script_id": {
          "type": "string"
        },
        "script_rev": {
          "type": "string"
        },
        "value": {
          "title": "Any"
        }
      }
    },
    "data-entity": {
      "title": "Data Entity",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "description": "The properties that are shared amongst all versions of the Data model.",
          "type": "object",
          "title": "Data Common",
          "required": [
            "job_id",
            "script_id",
            "script_rev",
            "value"
          ],
          "properties": {
            "job_id": {
              "type": "string"
            },
            "script_id": {
              "type": "string"
            },
            "script_rev": {
              "type": "string"
            },
            "value": {
              "title": "Any"
            }
          }
        }
      ]
    },
    "data-output": {
      "description": "The properties that are included when fetching a list of Data.",
      "title": "Data Output",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "type": "object",
          "required": [
            "job_id",
            "script_id"
          ],
          "properties": {
            "job_id": {
              "type": "string"
            },
            "script_id": {
              "type": "string"
            },
            "script_rev": {
              "type": "string"
            }
          }
        }
      ]
    },
    "data-output-detailed": {
      "description": "The properties that are included when fetching a single Data.",
      "title": "Data Output Detailed",
      "allOf": [
        {
          "title": "Data Entity",
          "allOf": [
            {
              "description": "Represents a database entity",
              "title": "Entity",
              "allOf": [
                {
                  "type": "object",
                  "required": [
                    "id",
                    "rev"
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "rev": {
                      "type": "string"
                    }
                  }
                },
                {
                  "description": "Response model for data creation endpoints",
                  "type": "object",
                  "title": "Metadata",
                  "required": [
                    "created_at"
                  ],
                  "properties": {
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                }
              ]
            },
            {
              "description": "The properties that are shared amongst all versions of the Data model.",
              "type": "object",
              "title": "Data Common",
              "required": [
                "job_id",
                "script_id",
                "script_rev",
                "value"
              ],
              "properties": {
                "job_id": {
                  "type": "string"
                },
                "script_id": {
                  "type": "string"
                },
                "script_rev": {
                  "type": "string"
                },
                "value": {
                  "title": "Any"
                }
              }
            }
          ]
        }
      ]
    },
    "data-update": {
      "description": "The properties that are allowed when updating a Data.",
      "type": "object",
      "title": "Data Update",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "title": "Any"
        }
      }
    },
    "entity": {
      "description": "Represents a database entity",
      "title": "Entity",
      "allOf": [
        {
          "type": "object",
          "required": [
            "id",
            "rev"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "rev": {
              "type": "string"
            }
          }
        },
        {
          "description": "Response model for data creation endpoints",
          "type": "object",
          "title": "Metadata",
          "required": [
            "created_at"
          ],
          "properties": {
            "created_at": {
              "type": "string"
            },
            "updated_at": {
              "type": "string"
            }
          }
        }
      ]
    },
    "execution-cause": {
      "description": "Execution cause",
      "type": "string",
      "title": "Execution Cause",
      "enum": [
        "unknown",
        "manual",
        "schedule",
        "hook"
      ]
    },
    "execution-common": {
      "description": "The properties that are shared amongst all versions of the Execution model.",
      "type": "object",
      "title": "Execution Common",
      "required": [
        "job_id",
        "script_id",
        "script_rev",
        "status",
        "cause"
      ],
      "properties": {
        "cause": {
          "description": "Execution cause",
          "type": "string",
          "title": "Execution Cause",
          "enum": [
            "unknown",
            "manual",
            "schedule",
            "hook"
          ]
        },
        "job_id": {
          "type": "string",
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        },
        "script_id": {
          "type": "string",
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        },
        "script_rev": {
          "type": "string"
        },
        "status": {
          "description": "Execution stats",
          "type": "string",
          "title": "Execution Status",
          "enum": [
            "unknown",
            "queued",
            "running",
            "completed",
            "cancelled",
            "errored"
          ]
        }
      }
    },
    "execution-input": {
      "description": "The properties that are allowed when creating or updating a Execution.",
      "type": "object",
      "title": "Execution Input",
      "required": [
        "scriptID"
      ],
      "properties": {
        "params": {
          "type": "object",
          "additionalProperties": {
            "title": "Any"
          }
        },
        "scriptID": {
          "type": "string",
          "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        }
      }
    },
    "execution-output": {
      "description": "The properties that are included when fetching a list of Executions.",
      "title": "Execution Output",
      "allOf": [
        {
          "type": "object"
        },
        {
          "description": "The properties that are shared amongst all versions of the Execution model.",
          "type": "object",
          "title": "Execution Common",
          "required": [
            "job_id",
            "script_id",
            "script_rev",
            "status",
            "cause"
          ],
          "properties": {
            "cause": {
              "description": "Execution cause",
              "type": "string",
              "title": "Execution Cause",
              "enum": [
                "unknown",
                "manual",
                "schedule",
                "hook"
              ]
            },
            "job_id": {
              "type": "string",
              "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
            },
            "script_id": {
              "type": "string",
              "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
            },
            "script_rev": {
              "type": "string"
            },
            "status": {
              "description": "Execution stats",
              "type": "string",
              "title": "Execution Status",
              "enum": [
                "unknown",
                "queued",
                "running",
                "completed",
                "cancelled",
                "errored"
              ]
            }
          }
        }
      ]
    },
    "execution-output-detailed": {
      "description": "The properties that are included when fetching a single Execution.",
      "title": "Execution Output Detailed",
      "allOf": [
        {
          "description": "The properties that are included when fetching a list of Executions.",
          "title": "Execution Output",
          "allOf": [
            {
              "type": "object"
            },
            {
              "description": "The properties that are shared amongst all versions of the Execution model.",
              "type": "object",
              "title": "Execution Common",
              "required": [
                "job_id",
                "script_id",
                "script_rev",
                "status",
                "cause"
              ],
              "properties": {
                "cause": {
                  "description": "Execution cause",
                  "type": "string",
                  "title": "Execution Cause",
                  "enum": [
                    "unknown",
                    "manual",
                    "schedule",
                    "hook"
                  ]
                },
                "job_id": {
                  "type": "string",
                  "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                },
                "script_id": {
                  "type": "string",
                  "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                },
                "script_rev": {
                  "type": "string"
                },
                "status": {
                  "description": "Execution stats",
                  "type": "string",
                  "title": "Execution Status",
                  "enum": [
                    "unknown",
                    "queued",
                    "running",
                    "completed",
                    "cancelled",
                    "errored"
                  ]
                }
              }
            }
          ]
        },
        {
          "type": "object",
          "properties": {
            "ended_at": {
              "type": "string"
            },
            "error": {
              "type": "string"
            },
            "logs": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "params": {
              "type": "object",
              "additionalProperties": {
                "title": "Any"
              }
            },
            "started_at": {
              "type": "string"
            }
          }
        }
      ]
    },
    "execution-status": {
      "description": "Execution stats",
      "type": "string",
      "title": "Execution Status",
      "enum": [
        "unknown",
        "queued",
        "running",
        "completed",
        "cancelled",
        "errored"
      ]
    },
    "metadata": {
      "description": "Response model for data creation endpoints",
      "type": "object",
      "title": "Metadata",
      "required": [
        "created_at"
      ],
      "properties": {
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        }
      }
    },
    "project-common": {
      "description": "The properties that are shared amongst all versions of the Project model.",
      "type": "object",
      "title": "Project Common",
      "required": [
        "name"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        }
      }
    },
    "project-create": {
      "description": "The properties that are shared amongst all versions of the Project model.",
      "type": "object",
      "title": "Project Common",
      "required": [
        "name"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        }
      }
    },
    "project-entity": {
      "description": "Represents a full Project entity.",
      "title": "Project Entity",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "description": "The properties that are shared amongst all versions of the Project model.",
          "type": "object",
          "title": "Project Common",
          "required": [
            "name"
          ],
          "properties": {
            "description": {
              "type": "string",
              "maxLength": 255,
              "minLength": 10
            },
            "name": {
              "type": "string",
              "maxLength": 100,
              "minLength": 3
            }
          }
        }
      ]
    },
    "project-output": {
      "description": "The properties that are included when fetching a list of Projects.",
      "title": "Project Output",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "project-output-detailed": {
      "description": "Represents a full Project entity.",
      "title": "Project Entity",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "description": "The properties that are shared amongst all versions of the Project model.",
          "type": "object",
          "title": "Project Common",
          "required": [
            "name"
          ],
          "properties": {
            "description": {
              "type": "string",
              "maxLength": 255,
              "minLength": 10
            },
            "name": {
              "type": "string",
              "maxLength": 100,
              "minLength": 3
            }
          }
        }
      ]
    },
    "project-update": {
      "description": "The properties that are shared amongst all versions of the Project model.",
      "type": "object",
      "title": "Project Common",
      "required": [
        "name"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        }
      }
    },
    "script-common": {
      "description": "The properties that are shared amongst all versions of the Script model.",
      "type": "object",
      "title": "Script Common",
      "required": [
        "name",
        "execution",
        "persistence"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "execution": {
          "description": "Represents script execution settings like query and params",
          "type": "object",
          "title": "Script Execution Settings",
          "required": [
            "query"
          ],
          "properties": {
            "params": {
              "type": "object",
              "additionalProperties": {
                "title": "Any"
              }
            },
            "query": {
              "type": "string",
              "minLength": 8
            }
          }
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        },
        "persistence": {
          "type": "object",
          "title": "Script Persistence",
          "required": [
            "enabled"
          ],
          "properties": {
            "enabled": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "script-create": {
      "description": "The properties that are shared amongst all versions of the Script model.",
      "type": "object",
      "title": "Script Common",
      "required": [
        "name",
        "execution",
        "persistence"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "execution": {
          "description": "Represents script execution settings like query and params",
          "type": "object",
          "title": "Script Execution Settings",
          "required": [
            "query"
          ],
          "properties": {
            "params": {
              "type": "object",
              "additionalProperties": {
                "title": "Any"
              }
            },
            "query": {
              "type": "string",
              "minLength": 8
            }
          }
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        },
        "persistence": {
          "type": "object",
          "title": "Script Persistence",
          "required": [
            "enabled"
          ],
          "properties": {
            "enabled": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "script-entity": {
      "title": "Script Entity",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "description": "The properties that are shared amongst all versions of the Script model.",
          "type": "object",
          "title": "Script Common",
          "required": [
            "name",
            "execution",
            "persistence"
          ],
          "properties": {
            "description": {
              "type": "string",
              "maxLength": 255,
              "minLength": 10
            },
            "execution": {
              "description": "Represents script execution settings like query and params",
              "type": "object",
              "title": "Script Execution Settings",
              "required": [
                "query"
              ],
              "properties": {
                "params": {
                  "type": "object",
                  "additionalProperties": {
                    "title": "Any"
                  }
                },
                "query": {
                  "type": "string",
                  "minLength": 8
                }
              }
            },
            "name": {
              "type": "string",
              "maxLength": 100,
              "minLength": 3
            },
            "persistence": {
              "type": "object",
              "title": "Script Persistence",
              "required": [
                "enabled"
              ],
              "properties": {
                "enabled": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      ]
    },
    "script-execution": {
      "description": "Represents script execution settings like query and params",
      "type": "object",
      "title": "Script Execution Settings",
      "required": [
        "query"
      ],
      "properties": {
        "params": {
          "type": "object",
          "additionalProperties": {
            "title": "Any"
          }
        },
        "query": {
          "type": "string",
          "minLength": 8
        }
      }
    },
    "script-output": {
      "description": "The properties that are included when fetching a list of Scripts.",
      "title": "Script Output",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "script-output-detailed": {
      "title": "Script Entity",
      "allOf": [
        {
          "description": "Represents a database entity",
          "title": "Entity",
          "allOf": [
            {
              "type": "object",
              "required": [
                "id",
                "rev"
              ],
              "properties": {
                "id": {
                  "type": "string"
                },
                "rev": {
                  "type": "string"
                }
              }
            },
            {
              "description": "Response model for data creation endpoints",
              "type": "object",
              "title": "Metadata",
              "required": [
                "created_at"
              ],
              "properties": {
                "created_at": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "description": "The properties that are shared amongst all versions of the Script model.",
          "type": "object",
          "title": "Script Common",
          "required": [
            "name",
            "execution",
            "persistence"
          ],
          "properties": {
            "description": {
              "type": "string",
              "maxLength": 255,
              "minLength": 10
            },
            "execution": {
              "description": "Represents script execution settings like query and params",
              "type": "object",
              "title": "Script Execution Settings",
              "required": [
                "query"
              ],
              "properties": {
                "params": {
                  "type": "object",
                  "additionalProperties": {
                    "title": "Any"
                  }
                },
                "query": {
                  "type": "string",
                  "minLength": 8
                }
              }
            },
            "name": {
              "type": "string",
              "maxLength": 100,
              "minLength": 3
            },
            "persistence": {
              "type": "object",
              "title": "Script Persistence",
              "required": [
                "enabled"
              ],
              "properties": {
                "enabled": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      ]
    },
    "script-persistence": {
      "type": "object",
      "title": "Script Persistence",
      "required": [
        "enabled"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        }
      }
    },
    "script-update": {
      "description": "The properties that are shared amongst all versions of the Script model.",
      "type": "object",
      "title": "Script Common",
      "required": [
        "name",
        "execution",
        "persistence"
      ],
      "properties": {
        "description": {
          "type": "string",
          "maxLength": 255,
          "minLength": 10
        },
        "execution": {
          "description": "Represents script execution settings like query and params",
          "type": "object",
          "title": "Script Execution Settings",
          "required": [
            "query"
          ],
          "properties": {
            "params": {
              "type": "object",
              "additionalProperties": {
                "title": "Any"
              }
            },
            "query": {
              "type": "string",
              "minLength": 8
            }
          }
        },
        "name": {
          "type": "string",
          "maxLength": 100,
          "minLength": 3
        },
        "persistence": {
          "type": "object",
          "title": "Script Persistence",
          "required": [
            "enabled"
          ],
          "properties": {
            "enabled": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "parameters": {
    "page": {
      "minimum": 1,
      "type": "integer",
      "format": "int32",
      "default": 1,
      "description": "Page number for queries",
      "name": "page",
      "in": "query"
    },
    "projectID": {
      "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
      "type": "string",
      "name": "projectID",
      "in": "path",
      "required": true
    },
    "scriptID": {
      "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
      "type": "string",
      "name": "scriptID",
      "in": "path",
      "required": true
    },
    "size": {
      "maximum": 100,
      "minimum": 1,
      "type": "integer",
      "format": "int32",
      "default": 10,
      "description": "Page size",
      "name": "size",
      "in": "query"
    },
    "status": {
      "enum": [
        "unknown",
        "queued",
        "running",
        "completed",
        "cancelled",
        "errored"
      ],
      "type": "string",
      "name": "status",
      "in": "query",
      "allowEmptyValue": true
    }
  },
  "responses": {
    "Error": {
      "description": "Error resonse",
      "schema": {
        "type": "string"
      }
    }
  }
}`))
}
